source 'https://rubygems.org'
  gem 'rails'
  gem 'pg'
  gem 'sass-rails'
  gem 'uglifier'
  gem 'coffee-rails'
  gem 'jquery-rails'
  gem 'turbolinks'
  gem 'jbuilder'
  gem 'sdoc'
  gem 'spring'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'launchy'
  gem 'pry'
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'bootstrap-sass'
  gem 'devise'
  gem 'factory_girl_rails'
  gem 'simplecov', require: false
  gem 'letter_opener'
  gem 'paperclip'
  gem 'byebug'
  gem 'web-console'

